feat(thumbnail): Add multipage thumbnail support.
freelawproject/doctor pull request #158
Opened 2023-01-17 16:46 UTC by ERosendo

This PR add multipage thumbnail support and resolves https://github.com/freelawproject/doctor/issues/126

2023-01-17 20:09 UTC, mlissner requested changes
Looks good. Zips are kind of annoying to deal with, but Python makes them friendly enough. 

One thing you could do, just for "fun" is to guard against [zip bombs](https://www.unforgettable.dk/). This isn't really getting input from random strangers on the Internet, but we've got the code to guard against them over on CourtListener, so it's easy to copy over. Start here:

https://github.com/freelawproject/courtlistener/blob/818ff303981cd96480e6797d8ec666e82a369aad/cl/recap/tasks.py#L410-L413

I also considered briefly whether just using a marker between files would work better. You could return a binary blob shaped like:

```
binary code for thumb 1
FLP_MARKER
binary code for thumb 2
FLP_MARKER
binary code for thumb 3
...
FLP_MARKER
binary code for thumb n
```

Then consumers just do:


```
data = response.content
files = data.split("FLP_MARKER")
```

That *is* a bit easier, but, meh, zips are standard and I guess that forces everything into memory which might be annoying. Anyway, it's a thought, but probably not worth doing.

Rest of the comments are pretty minor.

2023-01-17 20:09 UTC, mlissner commented on README.md
> +     -F 'pages="[1,2,3,4]"'
Is `-F` right?

2023-01-17 20:09 UTC, mlissner commented on doctor/views.py
> +        f.write(form.cleaned_data["file"].read())
You can use a `NamedTemporaryFile` as a context handler:

```suggestion
    with NamedTemporaryFile(suffix=".pdf", mode="r+b") as tmp_file:
        tmp_file.write(form.cleaned_data["file"].read())
```

2023-01-17 20:09 UTC, mlissner commented on README.md
> +     -F 'pages="[1,2,3,4]"'
This should also document how to set the dimensions of the thumbnails and what the setting does.

2023-01-17 20:09 UTC, mlissner commented on doctor/tests.py
> +        )
When you provide your own `msg` parameter to an assertion, you have the challenge of doing better than the default. The default tells you the expectation, result, and diff. Yours just provide failure messages without the result or the expectation, and so are not as good, I think. I'd either remove your `msg` parameters completely, or make them better.

2023-01-17 20:09 UTC, mlissner commented on doctor/tests.py
> +                listOfiles = sorted(zipObj.namelist())
I bet you could do this with a bytesIO object instead of writing/reading to disk, and gain a bit of performance, but it's not worth re-doing now. Just a thought, really.

2023-01-17 23:50 UTC, ERosendo commented on doctor/views.py
> +        f.write(form.cleaned_data["file"].read())
You're right. 

Changed. Thanks.

2023-01-17 23:54 UTC, ERosendo commented on README.md
> +     -F 'pages="[1,2,3,4]"'
Yes, the `-F` command line option tells `Curl` to send HTML data to the server in `multipart/form-data` format. I will update the README file to include the `max_dimension` parameter.

2023-01-18 00:40 UTC, ERosendo commented
Thank you! @mlissner I've applied the requested changes.

We can also use the [FileExtensionValidator](https://docs.djangoproject.com/en/4.1/ref/validators/#fileextensionvalidator) to limit the input of this new service. This class from `django.core.validators` checks the extension of the file that's been uploaded and raises a [ValidationError](https://docs.djangoproject.com/en/4.2/ref/exceptions/#django.core.exceptions.ValidationError) if the extension is not allowed. If We use this validator class, the `ThumbnailForm` will look like this:

```python
class ThumbnailForm(forms.Form):
  file = forms.FileField(
      label="document",
      required=True,
      validators=[FileExtensionValidator(["pdf"])],
  )
  max_dimension = forms.IntegerField(label="max-dimension", required=False)
  pages = forms.Field(label="pages", required=False)
```

Let me know what you think.

2023-01-18 00:57 UTC, mlissner commented
Sure, might as well use the validator, why not.

2023-01-18 00:59 UTC, mlissner commented
The rest looks good. If you want to do the validator, go for it. If you want to add the zip bomb protection, go for it. Whatever you do, please merge when you're happy.

2023-01-18 00:59 UTC, mlissner approved these changes

2023-01-18 01:48 UTC, merged